name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - working-directory: cookibud-front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run lint
          npm run format:check

  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - working-directory: cookibud-api
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-lock.txt
          pylint **/*.py
          black --check .
          isort . --check-only

  test-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - working-directory: cookibud-front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run test:coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: cookibud-front/coverage/lcov.info

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - working-directory: cookibud-api
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-lock.txt
          pytest . --cov=./ --cov-report=lcov:coverage/lcov.info
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: cookibud-api/coverage/lcov.info

  sonarqube-front:
    name: SonarQube
    needs: test-front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download a single artifact
        uses: actions/download-artifact@v5
        with:
          name: coverage-report
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Soilhat_cookibud-front
            -Dsonar.organization=soilhat
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.typescript.lcov.reportPaths=lcov.info
            -Dsonar.coverage.exclusions=**/tests/**,**/stories/**,**/*.spec.tsx,**/*.spec.ts,**/*.config.ts

  sonarqube-api:
    name: SonarQube
    needs: test-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download a single artifact
        uses: actions/download-artifact@v5
        with:
          name: coverage-report
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Soilhat_cookibud-api
            -Dsonar.organization=soilhat
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.lcov.reportPaths=lcov.info


  deploy:
    name: Deploy to Local runner
    needs: [lint-front, lint-api, test-front, test-api, sonarqube-front, sonarqube-api]
    runs-on: self-hosted
    steps:
      - name: Deploy with Docker Compose
        uses: actions/checkout@v4
      - run: |
          docker-compose up -d --build
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
